name: Flutter CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'

    - name: Install dependencies
      run: flutter pub get

    - name: Build project
      run: flutter build apk --debug

    - name: Run analyzer (optional)
      run: flutter analyze

    - name: Run tests (optional)
      run: flutter test